# Generated by Django 4.2.20 on 2025-04-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cznic_auctions', '0003_auctionslist_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionslist',
            name='template',
            field=models.CharField(blank=True, choices=[('cznic_auctions/list.html', 'Default'), ('cznic_auctions/list_bids_price.html', 'Bids, Price')], max_length=255, null=True, verbose_name='Template'),
        ),
    ]
