# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.05.4&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aind_slurm_rest_v2.models.slurm_v0041_post_job_submit_request_jobs_inner_rlimits_memlock import SlurmV0041PostJobSubmitRequestJobsInnerRlimitsMemlock

class TestSlurmV0041PostJobSubmitRequestJobsInnerRlimitsMemlock(unittest.TestCase):
    """SlurmV0041PostJobSubmitRequestJobsInnerRlimitsMemlock unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SlurmV0041PostJobSubmitRequestJobsInnerRlimitsMemlock:
        """Test SlurmV0041PostJobSubmitRequestJobsInnerRlimitsMemlock
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SlurmV0041PostJobSubmitRequestJobsInnerRlimitsMemlock`
        """
        model = SlurmV0041PostJobSubmitRequestJobsInnerRlimitsMemlock()
        if include_optional:
            return SlurmV0041PostJobSubmitRequestJobsInnerRlimitsMemlock(
                set = True,
                infinite = True,
                number = 56
            )
        else:
            return SlurmV0041PostJobSubmitRequestJobsInnerRlimitsMemlock(
        )
        """

    def testSlurmV0041PostJobSubmitRequestJobsInnerRlimitsMemlock(self):
        """Test SlurmV0041PostJobSubmitRequestJobsInnerRlimitsMemlock"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
