# Generated by Django 3.0.3 on 2021-01-18 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policyholder', '0007_auto_20210118_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpolicyholder',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', null=True),
        ),
        migrations.AlterField(
            model_name='historicalpolicyholder',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', null=True),
        ),
        migrations.AlterField(
            model_name='historicalpolicyholder',
            name='date_valid_from',
            field=models.DateTimeField(db_column='DateValidFrom', default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='historicalpolicyholder',
            name='date_valid_to',
            field=models.DateTimeField(blank=True, db_column='DateValidTo', null=True),
        ),
        migrations.AlterField(
            model_name='historicalpolicyholdercontributionplan',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', null=True),
        ),
        migrations.AlterField(
            model_name='historicalpolicyholdercontributionplan',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', null=True),
        ),
        migrations.AlterField(
            model_name='historicalpolicyholdercontributionplan',
            name='date_valid_from',
            field=models.DateTimeField(db_column='DateValidFrom', default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='historicalpolicyholdercontributionplan',
            name='date_valid_to',
            field=models.DateTimeField(blank=True, db_column='DateValidTo', null=True),
        ),
        migrations.AlterField(
            model_name='historicalpolicyholderinsuree',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', null=True),
        ),
        migrations.AlterField(
            model_name='historicalpolicyholderinsuree',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', null=True),
        ),
        migrations.AlterField(
            model_name='historicalpolicyholderinsuree',
            name='date_valid_from',
            field=models.DateTimeField(db_column='DateValidFrom', default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='historicalpolicyholderinsuree',
            name='date_valid_to',
            field=models.DateTimeField(blank=True, db_column='DateValidTo', null=True),
        ),
        migrations.AlterField(
            model_name='historicalpolicyholderuser',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', null=True),
        ),
        migrations.AlterField(
            model_name='historicalpolicyholderuser',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', null=True),
        ),
        migrations.AlterField(
            model_name='historicalpolicyholderuser',
            name='date_valid_from',
            field=models.DateTimeField(db_column='DateValidFrom', default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='historicalpolicyholderuser',
            name='date_valid_to',
            field=models.DateTimeField(blank=True, db_column='DateValidTo', null=True),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', null=True),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', null=True),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='date_valid_from',
            field=models.DateTimeField(db_column='DateValidFrom', default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='date_valid_to',
            field=models.DateTimeField(blank=True, db_column='DateValidTo', null=True),
        ),
        migrations.AlterField(
            model_name='policyholdercontributionplan',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', null=True),
        ),
        migrations.AlterField(
            model_name='policyholdercontributionplan',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', null=True),
        ),
        migrations.AlterField(
            model_name='policyholdercontributionplan',
            name='date_valid_from',
            field=models.DateTimeField(db_column='DateValidFrom', default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='policyholdercontributionplan',
            name='date_valid_to',
            field=models.DateTimeField(blank=True, db_column='DateValidTo', null=True),
        ),
        migrations.AlterField(
            model_name='policyholderinsuree',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', null=True),
        ),
        migrations.AlterField(
            model_name='policyholderinsuree',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', null=True),
        ),
        migrations.AlterField(
            model_name='policyholderinsuree',
            name='date_valid_from',
            field=models.DateTimeField(db_column='DateValidFrom', default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='policyholderinsuree',
            name='date_valid_to',
            field=models.DateTimeField(blank=True, db_column='DateValidTo', null=True),
        ),
        migrations.AlterField(
            model_name='policyholderuser',
            name='date_created',
            field=models.DateTimeField(db_column='DateCreated', null=True),
        ),
        migrations.AlterField(
            model_name='policyholderuser',
            name='date_updated',
            field=models.DateTimeField(db_column='DateUpdated', null=True),
        ),
        migrations.AlterField(
            model_name='policyholderuser',
            name='date_valid_from',
            field=models.DateTimeField(db_column='DateValidFrom', default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='policyholderuser',
            name='date_valid_to',
            field=models.DateTimeField(blank=True, db_column='DateValidTo', null=True),
        ),
    ]
