from eskmo.base.interface import UserReferable as UserReferable
from eskmo.base.mvtype import ACCOUNT_TYPE as ACCOUNT_TYPE, ID as ID, PID as PID, QUOTE as QUOTE, STOCK as STOCK, SYMBOL_CODE as SYMBOL_CODE
from eskmo.const.skcom import API_SKCOM as API_SKCOM
from eskmo.internal.balance import AccountBalance as AccountBalance

class Account(UserReferable):
    def __init__(self, user, accountId) -> None: ...
    @property
    def summary(self): ...
    @property
    def id(self): ...
    @property
    def name(self): ...
    @property
    def balance(self, symbol: str = None) -> AccountBalance: ...
    @name.setter
    def name(self, val) -> None: ...
    def subscribe(self, market, tag, *args, **kwargs) -> None: ...
    def unsubscribe(self, market, tag, *args, **kwargs) -> None: ...

class StockAccount(Account):
    def __init__(self, user, accountId) -> None: ...
    def subscribe_quote(self, symbol) -> None: ...

class FutureAccount(Account):
    def __init__(self, user, accountId) -> None: ...
