# Generated by Django 3.2.25 on 2025-04-14 20:16

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('texsitecore', '0004_basepage_show_in_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='XperiencePage',
            fields=[
                (
                    'basepage_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='texsitecore.basepage',
                    ),
                ),
                (
                    'body',
                    wagtail.fields.StreamField(
                        [
                            ('paragraph', wagtail.blocks.RichTextBlock()),
                            (
                                'carousel',
                                wagtail.blocks.ListBlock(
                                    wagtail.images.blocks.ImageChooserBlock(),
                                    min_num=2,
                                    template='texsitexperience/blocks/carousel.html',
                                ),
                            ),
                            ('raw_html', wagtail.blocks.RawHTMLBlock()),
                        ],
                        use_json_field=True,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Xperience Page (texsite.xperience)',
            },
            bases=('texsitecore.basepage',),
        ),
    ]
