# Generated by Django 3.2.25 on 2025-04-18 17:05

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('texsitexperience', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xperiencepage',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    (
                        'paragraph',
                        wagtail.blocks.RichTextBlock(icon='pilcrow'),
                    ),
                    (
                        'teaser_image',
                        wagtail.images.blocks.ImageChooserBlock(
                            icon='image',
                            template='texsitexperience/blocks/teaser_image.html',
                        ),
                    ),
                    (
                        'carousel',
                        wagtail.blocks.ListBlock(
                            wagtail.images.blocks.ImageChooserBlock(),
                            icon='image',
                            min_num=2,
                            template='texsitexperience/blocks/carousel.html',
                        ),
                    ),
                    (
                        'promoted_pages',
                        wagtail.blocks.ListBlock(
                            wagtail.blocks.StructBlock(
                                [
                                    (
                                        'page',
                                        wagtail.blocks.PageChooserBlock(
                                            required=True
                                        ),
                                    ),
                                    (
                                        'teaser',
                                        wagtail.images.blocks.ImageChooserBlock(
                                            required=True
                                        ),
                                    ),
                                ]
                            ),
                            icon='pick',
                            template='texsitexperience/blocks/promoted_pages.html',
                        ),
                    ),
                    (
                        'article_listing',
                        wagtail.blocks.StructBlock(
                            [
                                ('parent', wagtail.blocks.PageChooserBlock()),
                                (
                                    'limit',
                                    wagtail.blocks.IntegerBlock(
                                        min_value=1, required=False
                                    ),
                                ),
                                (
                                    'newest_first',
                                    wagtail.blocks.BooleanBlock(
                                        default=True, required=False
                                    ),
                                ),
                            ],
                            icon='list-ul',
                            template='texsitexperience/blocks/article_listing.html',
                        ),
                    ),
                    ('raw_html', wagtail.blocks.RawHTMLBlock()),
                ],
                use_json_field=True,
            ),
        ),
    ]
