# coding: utf-8

"""
    Majordomo AI

    This is a API specification for Majordomo AI

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from majordomo_ai.models.monitor_profile import MonitorProfile

class TestMonitorProfile(unittest.TestCase):
    """MonitorProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MonitorProfile:
        """Test MonitorProfile
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MonitorProfile`
        """
        model = MonitorProfile()
        if include_optional:
            return MonitorProfile(
                name = '',
                provider = 1,
                access_key = majordomo_ai.models.monitor_access_key.MonitorAccessKey(
                    api_key = '', ),
                access_info = majordomo_ai.models.monitor_profile_response.Monitor Profile Response(
                    host = '', )
            )
        else:
            return MonitorProfile(
                name = '',
                provider = 1,
        )
        """

    def testMonitorProfile(self):
        """Test MonitorProfile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
