# coding: utf-8

"""
    Majordomo AI

    This is a API specification for Majordomo AI

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from majordomo_ai.models.query_modes import QueryModes

class TestQueryModes(unittest.TestCase):
    """QueryModes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQueryModes(self):
        """Test QueryModes"""
        # inst = QueryModes()

if __name__ == '__main__':
    unittest.main()
