# coding: utf-8

"""
    Majordomo AI

    This is a API specification for Majordomo AI

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from majordomo_ai.api.ingest_api import IngestApi


class TestIngestApi(unittest.TestCase):
    """IngestApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IngestApi()

    def tearDown(self) -> None:
        pass

    def test_create_data_store(self) -> None:
        """Test case for create_data_store

        Create a data store.
        """
        pass

    def test_create_ingest_pipeline(self) -> None:
        """Test case for create_ingest_pipeline

        Create ingest pipeline.
        """
        pass

    def test_data_store_ingest(self) -> None:
        """Test case for data_store_ingest

        Data store ingestion.
        """
        pass

    def test_data_store_upload(self) -> None:
        """Test case for data_store_upload

        Data store ingest local file.
        """
        pass

    def test_delete_data_stores(self) -> None:
        """Test case for delete_data_stores

        Delete data store.
        """
        pass

    def test_delete_ingest_pipelines(self) -> None:
        """Test case for delete_ingest_pipelines

        Delete ingest pipeline.
        """
        pass

    def test_delete_vector_store_files(self) -> None:
        """Test case for delete_vector_store_files

        Delete vector stores information.
        """
        pass

    def test_get_data_stores(self) -> None:
        """Test case for get_data_stores

        List data stores.
        """
        pass

    def test_get_ingest_pipelines(self) -> None:
        """Test case for get_ingest_pipelines

        Get ingest pipeline.
        """
        pass

    def test_get_vector_stores(self) -> None:
        """Test case for get_vector_stores

        Get vector stores information.
        """
        pass

    def test_run_ingest_pipeline(self) -> None:
        """Test case for run_ingest_pipeline

        Run ingest pipeline.
        """
        pass

    def test_update_data_store(self) -> None:
        """Test case for update_data_store

        Update data store.
        """
        pass

    def test_update_ingest_pipeline(self) -> None:
        """Test case for update_ingest_pipeline

        Update ingest pipeline.
        """
        pass


if __name__ == '__main__':
    unittest.main()
