# coding: utf-8

"""
    Majordomo AI

    This is a API specification for Majordomo AI

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from majordomo_ai.models.app_profiles import AppProfiles

class TestAppProfiles(unittest.TestCase):
    """AppProfiles unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppProfiles:
        """Test AppProfiles
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppProfiles`
        """
        model = AppProfiles()
        if include_optional:
            return AppProfiles(
                app_profiles = [
                    majordomo_ai.models.application_profile_response.Application Profile Response(
                        config = majordomo_ai.models.app_profile.AppProfile(
                            name = '', 
                            workspace = '{"name":"Engineering"}', 
                            app_type = 1, 
                            access_info = {
                                'key' : null
                                }, 
                            shared_users = [
                                ''
                                ], ), 
                        supported_operations = [
                            1
                            ], 
                        created_by = '', 
                        created_at = 56, 
                        last_update = 56, )
                    ],
                shared_profiles = [
                    majordomo_ai.models.application_profile_response.Application Profile Response(
                        config = majordomo_ai.models.app_profile.AppProfile(
                            name = '', 
                            workspace = '{"name":"Engineering"}', 
                            app_type = 1, 
                            access_info = {
                                'key' : null
                                }, 
                            shared_users = [
                                ''
                                ], ), 
                        supported_operations = [
                            1
                            ], 
                        created_by = '', 
                        created_at = 56, 
                        last_update = 56, )
                    ]
            )
        else:
            return AppProfiles(
        )
        """

    def testAppProfiles(self):
        """Test AppProfiles"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
