
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-04-29T17:04:59-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "6329ae1259afa234d4bb308672fb20cf5295f9c6",
 "version": "2.60.1rc0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
