from _typeshed import Incomplete
from enum import Enum

class EskmoError(Enum):
    BASE = 'BaseError'
    LOGIN = 'LoginError'
    ACCOUNT_TAG_EXISTS = 'AccountTagExistsError'
    SERVER = 'ServerError'
    OPERATION_FAILED = 'OperationFailedError'
    NETWORK = 'NetworkError'
    REQUEST_TIMEOUT = 'RequestTimeoutError'

ERROR_HIERARCHY: Incomplete

class BaseError(Exception): ...
class LoginError(BaseError): ...
class AccountTagExistsError(LoginError): ...
class ServerError(BaseError): ...
class OperationFailedError(BaseError): ...
class NetworkError(OperationFailedError): ...
class RequestTimeoutError(NetworkError): ...
