# DEFAULT_OTLP_TYPE = "otlp"
# DEFAULT_OTLP_GRPC_ENDPOINT = "localhost:4317"

# DEFAULT_OTLP_TRACES_HTTP_ENDPOINT = "http://localhost:4317/v1/traces"
# DEFAULT_OTLP_METRICS_HTTP_ENDPOINT = "http://localhost:4318/v1/metrics"

# OTLP_TYPE = "PYEQX_OTLP_TYPE"
# OTLP_TRACES_ENDPOINT_KEY = "PYEQX_OTLP_TRACES_ENDPOINT"
# OTLP_METRICS_ENDPOINT_KEY = "PYEQX_OTLP_METRICS_ENDPOINT"


DEFAULT_OTLP_PROTOCOL = "grpc"
DEFAULT_OTLP_ENDPOINT = "localhost:4317"
