# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from digitalkin_proto.digitalkin.cost.v1 import cost_pb2 as digitalkin_dot_cost_dot_v1_dot_cost__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in digitalkin/cost/v1/cost_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CostServiceStub(object):
    """CostService: Service to manage costs
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddCost = channel.unary_unary(
                '/digitalkin.cost.v1.CostService/AddCost',
                request_serializer=digitalkin_dot_cost_dot_v1_dot_cost__pb2.AddCostRequest.SerializeToString,
                response_deserializer=digitalkin_dot_cost_dot_v1_dot_cost__pb2.AddCostResponse.FromString,
                _registered_method=True)
        self.GetCostsByMission = channel.unary_unary(
                '/digitalkin.cost.v1.CostService/GetCostsByMission',
                request_serializer=digitalkin_dot_cost_dot_v1_dot_cost__pb2.GetCostsByMissionRequest.SerializeToString,
                response_deserializer=digitalkin_dot_cost_dot_v1_dot_cost__pb2.GetCostsByMissionResponse.FromString,
                _registered_method=True)
        self.GetCostsByName = channel.unary_unary(
                '/digitalkin.cost.v1.CostService/GetCostsByName',
                request_serializer=digitalkin_dot_cost_dot_v1_dot_cost__pb2.GetCostsByNameRequest.SerializeToString,
                response_deserializer=digitalkin_dot_cost_dot_v1_dot_cost__pb2.GetCostsByNameResponse.FromString,
                _registered_method=True)
        self.GetCostsByType = channel.unary_unary(
                '/digitalkin.cost.v1.CostService/GetCostsByType',
                request_serializer=digitalkin_dot_cost_dot_v1_dot_cost__pb2.GetCostsByTypeRequest.SerializeToString,
                response_deserializer=digitalkin_dot_cost_dot_v1_dot_cost__pb2.GetCostsByTypeResponse.FromString,
                _registered_method=True)


class CostServiceServicer(object):
    """CostService: Service to manage costs
    """

    def AddCost(self, request, context):
        """AddCost: Add a cost
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCostsByMission(self, request, context):
        """GetCostsByMission: Get a cost by Mission ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCostsByName(self, request, context):
        """GetCostsByName: Get costs by name
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCostsByType(self, request, context):
        """GetCostsByType: Get costs by type
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CostServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddCost': grpc.unary_unary_rpc_method_handler(
                    servicer.AddCost,
                    request_deserializer=digitalkin_dot_cost_dot_v1_dot_cost__pb2.AddCostRequest.FromString,
                    response_serializer=digitalkin_dot_cost_dot_v1_dot_cost__pb2.AddCostResponse.SerializeToString,
            ),
            'GetCostsByMission': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCostsByMission,
                    request_deserializer=digitalkin_dot_cost_dot_v1_dot_cost__pb2.GetCostsByMissionRequest.FromString,
                    response_serializer=digitalkin_dot_cost_dot_v1_dot_cost__pb2.GetCostsByMissionResponse.SerializeToString,
            ),
            'GetCostsByName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCostsByName,
                    request_deserializer=digitalkin_dot_cost_dot_v1_dot_cost__pb2.GetCostsByNameRequest.FromString,
                    response_serializer=digitalkin_dot_cost_dot_v1_dot_cost__pb2.GetCostsByNameResponse.SerializeToString,
            ),
            'GetCostsByType': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCostsByType,
                    request_deserializer=digitalkin_dot_cost_dot_v1_dot_cost__pb2.GetCostsByTypeRequest.FromString,
                    response_serializer=digitalkin_dot_cost_dot_v1_dot_cost__pb2.GetCostsByTypeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'digitalkin.cost.v1.CostService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('digitalkin.cost.v1.CostService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CostService(object):
    """CostService: Service to manage costs
    """

    @staticmethod
    def AddCost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/digitalkin.cost.v1.CostService/AddCost',
            digitalkin_dot_cost_dot_v1_dot_cost__pb2.AddCostRequest.SerializeToString,
            digitalkin_dot_cost_dot_v1_dot_cost__pb2.AddCostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCostsByMission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/digitalkin.cost.v1.CostService/GetCostsByMission',
            digitalkin_dot_cost_dot_v1_dot_cost__pb2.GetCostsByMissionRequest.SerializeToString,
            digitalkin_dot_cost_dot_v1_dot_cost__pb2.GetCostsByMissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCostsByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/digitalkin.cost.v1.CostService/GetCostsByName',
            digitalkin_dot_cost_dot_v1_dot_cost__pb2.GetCostsByNameRequest.SerializeToString,
            digitalkin_dot_cost_dot_v1_dot_cost__pb2.GetCostsByNameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCostsByType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/digitalkin.cost.v1.CostService/GetCostsByType',
            digitalkin_dot_cost_dot_v1_dot_cost__pb2.GetCostsByTypeRequest.SerializeToString,
            digitalkin_dot_cost_dot_v1_dot_cost__pb2.GetCostsByTypeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
