
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-04-28T04:53:33+0000",
 "dirty": true,
 "error": null,
 "full-revisionid": "209db2289020d0c0277832c5d29808875ef6386d",
 "version": "0.11.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
