from _typeshed import Incomplete

class Tracer:
    fnList: Incomplete
    fnDict: Incomplete
    def __init__(self) -> None: ...
    def trace_add(self, fn, traceId: Incomplete | None = None) -> None: ...
    def trace_remove(self, traceId) -> None: ...
    def start_trace(self, *args) -> None: ...
    def onTrigger(self, *args) -> None: ...
