from dataclasses import dataclass, field

@dataclass
class Waitable:
    category: str = ...
    start: str = ...
    success: str = ...
    fail: str = ...
    tags: list = field(default_factory=[])
