from eskmo.base.mvtype import THREAD_ZMQ_PREFIX as THREAD_ZMQ_PREFIX
from eskmo.utils.misc import renameThread as renameThread

def startEventLoop() -> None: ...
def stopEventLoop() -> None: ...
def coinitialize(func): ...
