from _typeshed import Incomplete

TESTING: str
MUS_PER_SEC: int
MS_PER_SEC: int
MINGUO_START_YEAR: int
TW_STOCK_PRICE_MULTIPLE: int

def frozen_dataclass(cls): ...
def hashId(truncate: Incomplete | None = None): ...
def toTWStockPriceDecimal(price): ...
def getDaysAgoFromTimestamp(timestamp, days): ...
def toADDateStr(time): ...
def isSKCOMStreamFinished(str): ...
def getDictFromSKCOMStream(str, list): ...
def toMinguoDateStr(time): ...
def parseTimeDiff(prev, now): ...
def toDollar(price): ...
def toCent(price): ...
def camelToSnake(name): ...
def threadStart(func): ...
def renameThread(name) -> None: ...
def isToday(timestamp): ...
def shortString(data, maxlen: int = 80): ...
def isSubset(dict1: dict, dict2: dict) -> bool: ...
