# coding: utf-8

"""
    Mauve Admin API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import mauve_client
from mauve_client.api.others_api import OthersApi  # noqa: E501
from mauve_client.rest import ApiException


class TestOthersApi(unittest.TestCase):
    """OthersApi unit test stubs"""

    def setUp(self):
        self.api = OthersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_ping_request_get(self):
        """Test case for get_ping_request_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
