# coding: utf-8

"""
    Mauve Admin API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import mauve_client
from mauve_client.models.search_prices_response import SearchPricesResponse  # noqa: E501
from mauve_client.rest import ApiException


class TestSearchPricesResponse(unittest.TestCase):
    """SearchPricesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSearchPricesResponse(self):
        """Test SearchPricesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = mauve_client.models.search_prices_response.SearchPricesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
