# Generated by Django 3.2.18 on 2023-02-25 19:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('texsitecore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basepage',
            options={'verbose_name': 'Basis Seite (texsite.core)'},
        ),
    ]
