# coding: utf-8

"""
    Majordomo AI

    This is a API specification for Majordomo AI

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DeploymentCommands(int, Enum):
    """
    The types of deployment commands.
    """

    """
    allowed enum values
    """
    DEPLOYMENT_COMMAND_NONE = 1
    DEPLOYMENT_COMMAND_START = 2
    DEPLOYMENT_COMMAND_STOP = 3
    DEPLOYMENT_COMMAND_ABORT = 4
    DEPLOYMENT_COMMAND_HEALTH_CHECK = 5

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DeploymentCommands from a JSON string"""
        return cls(json.loads(json_str))


