# coding: utf-8

"""
    Majordomo AI

    This is a API specification for Majordomo AI

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ModelProviders(int, Enum):
    """
    The list of model providers supported
    """

    """
    allowed enum values
    """
    PROVIDER_OPENAI = 1
    PROVIDER_ANTHROPIC = 2
    PROVIDER_AZURE_OPENAI = 3
    PROVIDER_AWS_BEDROCK = 4
    PROVIDER_SELF_HOSTED = 5

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ModelProviders from a JSON string"""
        return cls(json.loads(json_str))


