from eskmo.base.mvtype import *
from _typeshed import Incomplete
from multiprocessing import Queue, SimpleQueue

class mvQueue:
    queueMaxsize: Incomplete
    def __init__(self, command, queueMaxsize: int = 100) -> None: ...
    def queue(self) -> Queue: ...
    def put(self, data): ...
    def get(self, data): ...
    def dict(self): ...

class mvSimpleQueue:
    def __init__(self, command) -> None: ...
    def queue(self) -> SimpleQueue: ...
    def put(self, data): ...
    def get(self, data): ...
    def dict(self): ...
