from google.api import annotations_pb2 as _annotations_pb2
from kessel.inventory.v1beta2 import streamed_list_objects_request_pb2 as _streamed_list_objects_request_pb2
from kessel.inventory.v1beta2 import streamed_list_objects_response_pb2 as _streamed_list_objects_response_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
