# coding: utf-8

"""
    Compass API

    #### Welcome to the DeFi API from [Compass Labs](https://www.compasslabs.ai)!  Our API allows you to interact and transact in DeFi with ease.  We help you construct your transactions via a **simple REST API**.   You maintain custody at all times and **sign** all transactions **yourself**.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from compass.api_client.models.body import Body

class TestBody(unittest.TestCase):
    """Body unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Body:
        """Test Body
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Body`
        """
        model = Body()
        if include_optional:
            return Body(
                token_in = '1INCH',
                token_out = '1INCH',
                fee = '0.01',
                amount_out = None,
                amount_in_maximum = None,
                wrap_eth = True,
                amount_in = None,
                amount_out_minimum = None,
                token0 = '1INCH',
                token1 = '1INCH',
                tick_lower = -887272.0,
                tick_upper = -887272.0,
                amount0_desired = None,
                amount1_desired = None,
                amount0_min = None,
                amount1_min = None,
                recipient = '',
                token_id = 56,
                percentage_for_withdrawal = None,
                asset = '1INCH',
                amount = None,
                interest_rate_mode = 'stable',
                on_behalf_of = '',
                token = '1INCH',
                contract_name = 'AaveV3Pool'
            )
        else:
            return Body(
                token_in = '1INCH',
                token_out = '1INCH',
                fee = '0.01',
                amount_out = None,
                amount_in_maximum = None,
                amount_in = None,
                token0 = '1INCH',
                token1 = '1INCH',
                tick_lower = -887272.0,
                tick_upper = -887272.0,
                amount0_desired = None,
                amount1_desired = None,
                amount0_min = None,
                amount1_min = None,
                recipient = '',
                token_id = 56,
                percentage_for_withdrawal = None,
                asset = '1INCH',
                amount = None,
                interest_rate_mode = 'stable',
                token = '1INCH',
                contract_name = 'AaveV3Pool',
        )
        """

    def testBody(self):
        """Test Body"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
