# coding: utf-8

"""
    Compass API

    #### Welcome to the DeFi API from [Compass Labs](https://www.compasslabs.ai)!  Our API allows you to interact and transact in DeFi with ease.  We help you construct your transactions via a **simple REST API**.   You maintain custody at all times and **sign** all transactions **yourself**.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from compass.api_client.api.aerodrome_basic_api import AerodromeBasicApi


class TestAerodromeBasicApi(unittest.TestCase):
    """AerodromeBasicApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AerodromeBasicApi()

    def tearDown(self) -> None:
        pass

    def test_aerodrome_basic_liquidity_provision_add_liquidity(self) -> None:
        """Test case for aerodrome_basic_liquidity_provision_add_liquidity

        Provide liquidity
        """
        pass

    def test_aerodrome_basic_liquidity_provision_add_liquidity_eth(self) -> None:
        """Test case for aerodrome_basic_liquidity_provision_add_liquidity_eth

        Provide liquidity using WETH
        """
        pass

    def test_aerodrome_basic_liquidity_provision_remove_liquidity(self) -> None:
        """Test case for aerodrome_basic_liquidity_provision_remove_liquidity

        Remove liquidity
        """
        pass

    def test_aerodrome_basic_liquidity_provision_remove_liquidity_eth(self) -> None:
        """Test case for aerodrome_basic_liquidity_provision_remove_liquidity_eth

        Remove liquidity using WETH
        """
        pass

    def test_aerodrome_basic_swap_eth_for_token(self) -> None:
        """Test case for aerodrome_basic_swap_eth_for_token

        Swap from ETH
        """
        pass

    def test_aerodrome_basic_swap_token_for_eth(self) -> None:
        """Test case for aerodrome_basic_swap_token_for_eth

        Swap token for ETH
        """
        pass

    def test_aerodrome_basic_swap_tokens(self) -> None:
        """Test case for aerodrome_basic_swap_tokens

        Swap
        """
        pass


if __name__ == '__main__':
    unittest.main()
