
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-05-01T10:01:16+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b564efc9361cfe3aa4147359ca80e509e6b0cf83",
 "version": "1.0.0a0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
