from setuptools import setup, find_packages

setup(
    name="global_parser_lib",
    version="0.1.8",
    description="A library for parsing various file types.",
    author="",
    author_email="foundersoffice@vaiaclimate.com",
    package_dir={"": "src"},
    packages=find_packages(where="src"),
    python_requires=">=3.8",
    install_requires=[
        "aiohttp",
        "requests",
        "openai-whisper",
        "pdfplumber",
        "pandas",
        "python-docx",
        "python-pptx",
        "huggingface_hub",
        "openai",
        "python-dotenv",
        "httpx",
        "fastapi",
        "boto3",
        "botocore",
        "transformers",
        "nltk",
        "bs4",
        "langdetect",
        "chardet",
        "pymongo",
        "pymupdf==1.25.4",
    ],
) 