from enum import Enum


class ResourceType(str, Enum):
    ARTICLE = "ARTICLE"
    DALLE = "DALLE"
    LLM_CALL = "LLM_CALL"
    LLM_CHEAP_CALL = "LLM_CHEAP_CALL"
    REDDIT_POST = "REDDIT_POST"
    REDDIT_POST_WITH_COMMENT = "REDDIT_POST_WITH_COMMENT"
    SUBREDDIT_INFO = "SUBREDDIT_INFO"
    YOUTUBE_CHANNEL_INFO = "YOUTUBE_CHANNEL_INFO"
    YOUTUBE_VIDEO = "YOUTUBE_VIDEO"
    YOUTUBE_VIDEO_WITH_COMMENT = "YOUTUBE_VIDEO_WITH_COMMENT"
    YOUTUBE_VIDEO_WITH_COMMENT_AND_TRANSCRIPT = "YOUTUBE_VIDEO_WITH_COMMENT_AND_TRANSCRIPT"
    YOUTUBE_VIDEO_WITH_TRANSCRIPT = "YOUTUBE_VIDEO_WITH_TRANSCRIPT"

    def __str__(self) -> str:
        return str(self.value)
