"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from latitudesh_python_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class VirtualNetworkAssignmentAttributesTypedDict(TypedDict):
    virtual_network_id: NotRequired[str]
    vid: NotRequired[int]
    server_id: NotRequired[str]
    description: NotRequired[str]
    status: NotRequired[str]


class VirtualNetworkAssignmentAttributes(BaseModel):
    virtual_network_id: Optional[str] = None

    vid: Optional[int] = None

    server_id: Optional[str] = None

    description: Optional[str] = None

    status: Optional[str] = None


class VirtualNetworkAssignmentTypedDict(TypedDict):
    id: NotRequired[str]
    attributes: NotRequired[VirtualNetworkAssignmentAttributesTypedDict]


class VirtualNetworkAssignment(BaseModel):
    id: Optional[str] = None

    attributes: Optional[VirtualNetworkAssignmentAttributes] = None
