# coding: utf-8

"""
    Mauve Admin API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Order(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'currency_code': 'str',
        'order_number': 'str',
        'order_date': 'datetime',
        'payment_method': 'str',
        'sales_channel': 'str',
        'shipment_method': 'str',
        'comment': 'str',
        'birthday': 'datetime',
        'vat_identification_number': 'str',
        'tax_number': 'str',
        'customer_number': 'str',
        'external_customer_number': 'str',
        'customer_group': 'str',
        'document_type': 'str',
        'discount_percentage': 'float',
        'billing_address': 'OrderAddress',
        'shipping_address': 'OrderAddress',
        'order_lines': 'list[OrderLine]',
        'payments': 'list[OrderPayment]'
    }

    attribute_map = {
        'currency_code': 'currencyCode',
        'order_number': 'orderNumber',
        'order_date': 'orderDate',
        'payment_method': 'paymentMethod',
        'sales_channel': 'salesChannel',
        'shipment_method': 'shipmentMethod',
        'comment': 'comment',
        'birthday': 'birthday',
        'vat_identification_number': 'vatIdentificationNumber',
        'tax_number': 'taxNumber',
        'customer_number': 'customerNumber',
        'external_customer_number': 'externalCustomerNumber',
        'customer_group': 'customerGroup',
        'document_type': 'documentType',
        'discount_percentage': 'discountPercentage',
        'billing_address': 'billingAddress',
        'shipping_address': 'shippingAddress',
        'order_lines': 'orderLines',
        'payments': 'payments'
    }

    def __init__(self, currency_code=None, order_number=None, order_date=None, payment_method=None, sales_channel=None, shipment_method=None, comment=None, birthday=None, vat_identification_number=None, tax_number=None, customer_number=None, external_customer_number=None, customer_group=None, document_type=None, discount_percentage=None, billing_address=None, shipping_address=None, order_lines=None, payments=None):  # noqa: E501
        """Order - a model defined in Swagger"""  # noqa: E501
        self._currency_code = None
        self._order_number = None
        self._order_date = None
        self._payment_method = None
        self._sales_channel = None
        self._shipment_method = None
        self._comment = None
        self._birthday = None
        self._vat_identification_number = None
        self._tax_number = None
        self._customer_number = None
        self._external_customer_number = None
        self._customer_group = None
        self._document_type = None
        self._discount_percentage = None
        self._billing_address = None
        self._shipping_address = None
        self._order_lines = None
        self._payments = None
        self.discriminator = None
        self.currency_code = currency_code
        if order_number is not None:
            self.order_number = order_number
        if order_date is not None:
            self.order_date = order_date
        if payment_method is not None:
            self.payment_method = payment_method
        if sales_channel is not None:
            self.sales_channel = sales_channel
        if shipment_method is not None:
            self.shipment_method = shipment_method
        if comment is not None:
            self.comment = comment
        if birthday is not None:
            self.birthday = birthday
        if vat_identification_number is not None:
            self.vat_identification_number = vat_identification_number
        if tax_number is not None:
            self.tax_number = tax_number
        if customer_number is not None:
            self.customer_number = customer_number
        if external_customer_number is not None:
            self.external_customer_number = external_customer_number
        if customer_group is not None:
            self.customer_group = customer_group
        if document_type is not None:
            self.document_type = document_type
        if discount_percentage is not None:
            self.discount_percentage = discount_percentage
        if billing_address is not None:
            self.billing_address = billing_address
        if shipping_address is not None:
            self.shipping_address = shipping_address
        if order_lines is not None:
            self.order_lines = order_lines
        if payments is not None:
            self.payments = payments

    @property
    def currency_code(self):
        """Gets the currency_code of this Order.  # noqa: E501

        Currency code (ISO 4217) (e.g. EUR, USD)  # noqa: E501

        :return: The currency_code of this Order.  # noqa: E501
        :rtype: str
        """
        return self._currency_code

    @currency_code.setter
    def currency_code(self, currency_code):
        """Sets the currency_code of this Order.

        Currency code (ISO 4217) (e.g. EUR, USD)  # noqa: E501

        :param currency_code: The currency_code of this Order.  # noqa: E501
        :type: str
        """
        if currency_code is None:
            raise ValueError("Invalid value for `currency_code`, must not be `None`")  # noqa: E501

        self._currency_code = currency_code

    @property
    def order_number(self):
        """Gets the order_number of this Order.  # noqa: E501

        Optional external, alphanumerical order number (in german: Auftrags-Nr.)  # noqa: E501

        :return: The order_number of this Order.  # noqa: E501
        :rtype: str
        """
        return self._order_number

    @order_number.setter
    def order_number(self, order_number):
        """Sets the order_number of this Order.

        Optional external, alphanumerical order number (in german: Auftrags-Nr.)  # noqa: E501

        :param order_number: The order_number of this Order.  # noqa: E501
        :type: str
        """

        self._order_number = order_number

    @property
    def order_date(self):
        """Gets the order_date of this Order.  # noqa: E501

        Optional order date (in german: Auftragsdatum)  # noqa: E501

        :return: The order_date of this Order.  # noqa: E501
        :rtype: datetime
        """
        return self._order_date

    @order_date.setter
    def order_date(self, order_date):
        """Sets the order_date of this Order.

        Optional order date (in german: Auftragsdatum)  # noqa: E501

        :param order_date: The order_date of this Order.  # noqa: E501
        :type: datetime
        """

        self._order_date = order_date

    @property
    def payment_method(self):
        """Gets the payment_method of this Order.  # noqa: E501

        Paymentmethod of the order (e.g. cash on delivery, debit, creditcard, PayPal) (in german: Zahlungsweise)  # noqa: E501

        :return: The payment_method of this Order.  # noqa: E501
        :rtype: str
        """
        return self._payment_method

    @payment_method.setter
    def payment_method(self, payment_method):
        """Sets the payment_method of this Order.

        Paymentmethod of the order (e.g. cash on delivery, debit, creditcard, PayPal) (in german: Zahlungsweise)  # noqa: E501

        :param payment_method: The payment_method of this Order.  # noqa: E501
        :type: str
        """

        self._payment_method = payment_method

    @property
    def sales_channel(self):
        """Gets the sales_channel of this Order.  # noqa: E501

        Sales-Channel of the document (in german: Verkaufskanal)  # noqa: E501

        :return: The sales_channel of this Order.  # noqa: E501
        :rtype: str
        """
        return self._sales_channel

    @sales_channel.setter
    def sales_channel(self, sales_channel):
        """Sets the sales_channel of this Order.

        Sales-Channel of the document (in german: Verkaufskanal)  # noqa: E501

        :param sales_channel: The sales_channel of this Order.  # noqa: E501
        :type: str
        """

        self._sales_channel = sales_channel

    @property
    def shipment_method(self):
        """Gets the shipment_method of this Order.  # noqa: E501

        Shipmentmethod of the order (e.g. standard, express) (in german: Versandart)  # noqa: E501

        :return: The shipment_method of this Order.  # noqa: E501
        :rtype: str
        """
        return self._shipment_method

    @shipment_method.setter
    def shipment_method(self, shipment_method):
        """Sets the shipment_method of this Order.

        Shipmentmethod of the order (e.g. standard, express) (in german: Versandart)  # noqa: E501

        :param shipment_method: The shipment_method of this Order.  # noqa: E501
        :type: str
        """

        self._shipment_method = shipment_method

    @property
    def comment(self):
        """Gets the comment of this Order.  # noqa: E501


        :return: The comment of this Order.  # noqa: E501
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """Sets the comment of this Order.


        :param comment: The comment of this Order.  # noqa: E501
        :type: str
        """

        self._comment = comment

    @property
    def birthday(self):
        """Gets the birthday of this Order.  # noqa: E501


        :return: The birthday of this Order.  # noqa: E501
        :rtype: datetime
        """
        return self._birthday

    @birthday.setter
    def birthday(self, birthday):
        """Sets the birthday of this Order.


        :param birthday: The birthday of this Order.  # noqa: E501
        :type: datetime
        """

        self._birthday = birthday

    @property
    def vat_identification_number(self):
        """Gets the vat_identification_number of this Order.  # noqa: E501

        Value added tax identification number (e.g. DE999999999)  # noqa: E501

        :return: The vat_identification_number of this Order.  # noqa: E501
        :rtype: str
        """
        return self._vat_identification_number

    @vat_identification_number.setter
    def vat_identification_number(self, vat_identification_number):
        """Sets the vat_identification_number of this Order.

        Value added tax identification number (e.g. DE999999999)  # noqa: E501

        :param vat_identification_number: The vat_identification_number of this Order.  # noqa: E501
        :type: str
        """

        self._vat_identification_number = vat_identification_number

    @property
    def tax_number(self):
        """Gets the tax_number of this Order.  # noqa: E501


        :return: The tax_number of this Order.  # noqa: E501
        :rtype: str
        """
        return self._tax_number

    @tax_number.setter
    def tax_number(self, tax_number):
        """Sets the tax_number of this Order.


        :param tax_number: The tax_number of this Order.  # noqa: E501
        :type: str
        """

        self._tax_number = tax_number

    @property
    def customer_number(self):
        """Gets the customer_number of this Order.  # noqa: E501

        Alphanumerical unique identifier of a customer (always end with \"-K\") (in german: Kunden-Nr.)  # noqa: E501

        :return: The customer_number of this Order.  # noqa: E501
        :rtype: str
        """
        return self._customer_number

    @customer_number.setter
    def customer_number(self, customer_number):
        """Sets the customer_number of this Order.

        Alphanumerical unique identifier of a customer (always end with \"-K\") (in german: Kunden-Nr.)  # noqa: E501

        :param customer_number: The customer_number of this Order.  # noqa: E501
        :type: str
        """

        self._customer_number = customer_number

    @property
    def external_customer_number(self):
        """Gets the external_customer_number of this Order.  # noqa: E501


        :return: The external_customer_number of this Order.  # noqa: E501
        :rtype: str
        """
        return self._external_customer_number

    @external_customer_number.setter
    def external_customer_number(self, external_customer_number):
        """Sets the external_customer_number of this Order.


        :param external_customer_number: The external_customer_number of this Order.  # noqa: E501
        :type: str
        """

        self._external_customer_number = external_customer_number

    @property
    def customer_group(self):
        """Gets the customer_group of this Order.  # noqa: E501

        The name of the customer group (needs to be a valid entry from the corresponding reference list)  # noqa: E501

        :return: The customer_group of this Order.  # noqa: E501
        :rtype: str
        """
        return self._customer_group

    @customer_group.setter
    def customer_group(self, customer_group):
        """Sets the customer_group of this Order.

        The name of the customer group (needs to be a valid entry from the corresponding reference list)  # noqa: E501

        :param customer_group: The customer_group of this Order.  # noqa: E501
        :type: str
        """

        self._customer_group = customer_group

    @property
    def document_type(self):
        """Gets the document_type of this Order.  # noqa: E501


        :return: The document_type of this Order.  # noqa: E501
        :rtype: str
        """
        return self._document_type

    @document_type.setter
    def document_type(self, document_type):
        """Sets the document_type of this Order.


        :param document_type: The document_type of this Order.  # noqa: E501
        :type: str
        """

        self._document_type = document_type

    @property
    def discount_percentage(self):
        """Gets the discount_percentage of this Order.  # noqa: E501

        Order discount rate in percentage  # noqa: E501

        :return: The discount_percentage of this Order.  # noqa: E501
        :rtype: float
        """
        return self._discount_percentage

    @discount_percentage.setter
    def discount_percentage(self, discount_percentage):
        """Sets the discount_percentage of this Order.

        Order discount rate in percentage  # noqa: E501

        :param discount_percentage: The discount_percentage of this Order.  # noqa: E501
        :type: float
        """

        self._discount_percentage = discount_percentage

    @property
    def billing_address(self):
        """Gets the billing_address of this Order.  # noqa: E501


        :return: The billing_address of this Order.  # noqa: E501
        :rtype: OrderAddress
        """
        return self._billing_address

    @billing_address.setter
    def billing_address(self, billing_address):
        """Sets the billing_address of this Order.


        :param billing_address: The billing_address of this Order.  # noqa: E501
        :type: OrderAddress
        """

        self._billing_address = billing_address

    @property
    def shipping_address(self):
        """Gets the shipping_address of this Order.  # noqa: E501


        :return: The shipping_address of this Order.  # noqa: E501
        :rtype: OrderAddress
        """
        return self._shipping_address

    @shipping_address.setter
    def shipping_address(self, shipping_address):
        """Sets the shipping_address of this Order.


        :param shipping_address: The shipping_address of this Order.  # noqa: E501
        :type: OrderAddress
        """

        self._shipping_address = shipping_address

    @property
    def order_lines(self):
        """Gets the order_lines of this Order.  # noqa: E501


        :return: The order_lines of this Order.  # noqa: E501
        :rtype: list[OrderLine]
        """
        return self._order_lines

    @order_lines.setter
    def order_lines(self, order_lines):
        """Sets the order_lines of this Order.


        :param order_lines: The order_lines of this Order.  # noqa: E501
        :type: list[OrderLine]
        """

        self._order_lines = order_lines

    @property
    def payments(self):
        """Gets the payments of this Order.  # noqa: E501


        :return: The payments of this Order.  # noqa: E501
        :rtype: list[OrderPayment]
        """
        return self._payments

    @payments.setter
    def payments(self, payments):
        """Sets the payments of this Order.


        :param payments: The payments of this Order.  # noqa: E501
        :type: list[OrderPayment]
        """

        self._payments = payments

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Order, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Order):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
