from eskmo.config.skcom import *
from eskmo.utils.logger import Logger as Logger

class SkcomInstaller:
    def install(self) -> None: ...
    def createFolderIfNotExists(self, folder): ...
    def copySKCOMDllToRoot(self, skcomDllPath) -> None: ...
    def runBatchAndWaitForDone(self, path) -> None: ...
    def waitForRegSvr32Finished(self) -> None: ...
