"""
    TMO spec version: 1.0.0
    Contact: project-email@sample.com
    Generated by: https://www.t-mobile.com/
    Signature: eVt+Qq45pAebKXwD39C31T72uwRnCHTXaReMm90leb8=
"""
"""
    TMO spec version: 1.0.0
    Contact: project-email@sample.com
    Generated by: https://www.t-mobile.com/
    Signature: dEVoqwny7+pdjd6BsCnL2vjHSLlbQZr/veQDYhcIRf0=
    """
"""
    TMO spec version: 1.0.0
    Contact: project-email@sample.com
    Generated by: https://www.t-mobile.com/
    Signature: 57ypwJ0kg92luAPyLXtRmGJS2XNe33IVwYYYXOKn+Bk=
    """

    