REMAIN_NUM: int

def getAllCores(): ...
def getRemainCores(cores_used): ...
def setProcessAffinity(pid, cores) -> None: ...
def getProcessAffinity(pid): ...
def calculateAffinityMask(cores): ...
def getCurrentCore(): ...
def processKill(pid=...) -> None: ...
def getSubprocesses(pid=...): ...
def killAllProcesses(pid=...) -> None: ...
