from abc import ABC
from datetime import datetime

class Updatable(ABC):
    def __init__(self, updated: datetime = None) -> None: ...
    @property
    def updated(self): ...
    def updateTime(self, updated: datetime = None): ...
