# Generated by Django 3.0.3 on 2020-12-14 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policyholder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpolicyholderuser',
            name='user',
            field=models.ForeignKey(blank=True, db_column='UserUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.TechnicalUser'),
        ),
        migrations.AlterField(
            model_name='policyholderuser',
            name='user',
            field=models.ForeignKey(db_column='UserUUID', on_delete=django.db.models.deletion.DO_NOTHING, to='core.TechnicalUser'),
        ),
    ]
