# Generated by Django 3.0.3 on 2020-12-14 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policyholder', '0002_auto_20201214_1237'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='historicalpolicyholderuser',
        #     name='user',
        #     field=models.ForeignKey(
        #         blank=True, db_column='UserUUID', db_constraint=False, null=True,
        #         on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.InteractiveUser'),
        # ),
        # migrations.AlterField(
        #     model_name='policyholderuser',
        #     name='user',
        #     field=models.ForeignKey(db_column='UserUUID', on_delete=django.db.models.deletion.DO_NOTHING,
        #                             to='core.InteractiveUser'),
        # ),
    ]
