# Generated by Django 3.0.3 on 2021-01-12 10:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_mutationlog_client_mutation_details'),
        ('policyholder', '0005_auto_20210111_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyHolderUserMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mutation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='policy_holder_user', to='core.MutationLog')),
                ('policy_holder_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='policyholder.PolicyHolderUser')),
            ],
            options={
                'db_table': 'policy_holder_user_PolicyHolderUserMutation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PolicyHolderMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mutation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='policy_holder', to='core.MutationLog')),
                ('policy_holder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='policyholder.PolicyHolder')),
            ],
            options={
                'db_table': 'policy_holder_PolicyHolderMutation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PolicyHolderInsureeMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mutation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='policy_holder_insuree', to='core.MutationLog')),
                ('policy_holder_insuree', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='policyholder.PolicyHolderInsuree')),
            ],
            options={
                'db_table': 'policy_holder_insuree_PolicyHolderInsureeMutation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PolicyHolderContributionPlanMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mutation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='policy_holder_contribution_plan', to='core.MutationLog')),
                ('policy_holder_contribution_plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='policyholder.PolicyHolderContributionPlan')),
            ],
            options={
                'db_table': 'policy_holder_contribution_plan_PolicyHolderContributionPlanMutation',
                'managed': True,
            },
        ),
    ]
