# Generated by Django 3.0.3 on 2021-04-08 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210324_1528'),
        ('policyholder', '0010_auto_20210126_1040'),
    ]

    operations = [

    ]
