# Generated by Django 3.2.16 on 2023-01-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policyholder', '0016_policyholder_roles_for_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalpolicyholder',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical policy holder', 'verbose_name_plural': 'historical policy holders'},
        ),
        migrations.AlterModelOptions(
            name='historicalpolicyholdercontributionplan',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical policy holder contribution plan', 'verbose_name_plural': 'historical policy holder contribution plans'},
        ),
        migrations.AlterModelOptions(
            name='historicalpolicyholderinsuree',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical policy holder insuree', 'verbose_name_plural': 'historical policy holder insurees'},
        ),
        migrations.AlterModelOptions(
            name='historicalpolicyholderuser',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical policy holder user', 'verbose_name_plural': 'historical policy holder users'},
        ),
        migrations.AlterField(
            model_name='historicalpolicyholder',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpolicyholdercontributionplan',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpolicyholderinsuree',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpolicyholderuser',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
