# Generated by Django 4.2.20 on 2025-04-22 17:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('wagtailcore', '0073_page_latest_revision'),
        ('texsitecore', '0004_basepage_show_in_footer'),
        ('texsitecleanblog', '0008_alter_cleanblogarticlepage_body'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CleanBlogArticlePage',
            new_name='CleanBlogPage',
        ),
        migrations.AlterModelOptions(
            name='cleanblogpage',
            options={'verbose_name': 'Clean Blog Page (texsite.cleanblog)'},
        ),
        migrations.RunSQL(
            """
            UPDATE
                texsitecleanblog_cleanblogarticleindexpage
            SET
                body = json_insert(body, '$[#]', json('{"type": "article_listing", "value": {"parent": ' || basepage_ptr_id || ', "limit": null, "newest_first": true}, "id": "cffabf43-e005-4e45-bf2a-9479105b4858"}'))
            """,
            '',
        ),
        migrations.RunSQL(
            """
            INSERT INTO
                texsitecleanblog_cleanblogpage
            SELECT
                *
            FROM
                texsitecleanblog_cleanblogarticleindexpage;
            """,
            '',
        ),
        migrations.RunSQL(
            """
            UPDATE
                wagtailcore_page
            SET
                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'texsitecleanblog' AND model = 'cleanblogpage'),
                latest_revision_id = null,
                live_revision_id = null
            WHERE
                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'texsitecleanblog' AND model = 'cleanblogarticleindexpage');
            """,
            '',
        ),
        migrations.RunSQL(
            """
            DELETE FROM
                wagtailcore_revision
            WHERE
                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'texsitecleanblog' AND model = 'cleanblogarticleindexpage');
            """,
            '',
        ),
        migrations.RunSQL(
            """
            DELETE FROM
                wagtailcore_pagelogentry
            WHERE
                content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'texsitecleanblog' AND model = 'cleanblogarticleindexpage');
            """,
            '',
        ),
        migrations.RunSQL(
            """
            DELETE FROM
                texsitecleanblog_cleanblogarticleindexpage;
            """,
            '',
        ),
        migrations.DeleteModel(
            name='CleanBlogArticleIndexPage',
        ),
    ]
