"""empty message

Revision ID: addd63e90cc7
Revises: 
Create Date: 2024-07-06 23:24:25.449397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'addd63e90cc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_dnd_db():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('output_keys', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade_dnd_db():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'output_keys')
    # ### end Alembic commands ###

