from eskmo import api as api
from eskmo.cli.install import API_INSTALL_MAPS as API_INSTALL_MAPS, API_UNINSTALL_MAPS as API_UNINSTALL_MAPS

def cli() -> None: ...
def install(api) -> None: ...
def uninstall(api) -> None: ...
def init() -> None: ...
def main() -> None: ...
