from typing import List, Tuple, Dict, Any

class DoctorDiagnosticAI:
    def __init__(self) -> None: ...
    def process_xray_image(self, img_path: str) -> Tuple[List[Tuple[str, float]], List[Dict[str, Any]]]: ...
    def create_medical_record(
        self,
        patient_info: str,
        symptoms: str,
        image_paths: List[str],
        include_xray_image: bool = ...
    ) -> str: ...
    def suggest_treatment(self, symptoms: str, pathologies_list: List[List[Tuple[str, float]]]) -> str: ...
    def reason_from_symptoms(self, symptoms: str) -> str: ...