from eskmo.base.mvtype import *
import abc
from abc import ABC, abstractmethod

class mvConnection(ABC, metaclass=abc.ABCMeta):
    def __init__(self, command) -> None: ...
    @property
    def command(self): ...
    @property
    def rfvc(self): ...
    @property
    def rfvp(self): ...
    @property
    def stvc(self): ...
    @property
    def stvp(self): ...
    @property
    def rfmc(self): ...
    @property
    def rfmp(self): ...
    @property
    def stmc(self): ...
    @property
    def stmp(self): ...
    def sendToManager(self, payload) -> None: ...
    def listenFromViewports(self): ...
    def sendToViewports(self, msg) -> None: ...
    def queueArray(self, mvqueues): ...
    @abstractmethod
    def listen(self, conns, queues): ...
