# Generated by Django 4.2.20 on 2025-04-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cznic_auctions', '0002_auctionslist_sort_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionslist',
            name='template',
            field=models.CharField(blank=True, choices=[], max_length=255, null=True, verbose_name='Template'),
        ),
    ]
