# Generated by Django 4.2.20 on 2025-04-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cznic_auctions', '0005_auctions_label_alter_auctionslist_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionslist',
            name='context',
            field=models.JSONField(blank=True, help_text='Extra values for the template. For example: home_url, bid_url, hide_icon_unwatch, show_bid_button.', null=True, verbose_name='Context'),
        ),
    ]
