"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from latitudesh_python_sdk.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class BandwidthPlanType(str, Enum):
    BANDWIDTH_PLAN = "bandwidth_plan"


class UsdTypedDict(TypedDict):
    monthly: NotRequired[int]
    hourly: NotRequired[int]


class Usd(BaseModel):
    monthly: Optional[int] = None

    hourly: Optional[int] = None


class BrlTypedDict(TypedDict):
    monthly: NotRequired[int]
    hourly: NotRequired[int]


class Brl(BaseModel):
    monthly: Optional[int] = None

    hourly: Optional[int] = None


class PricingTypedDict(TypedDict):
    usd: NotRequired[UsdTypedDict]
    brl: NotRequired[BrlTypedDict]


class Pricing(BaseModel):
    usd: Optional[Usd] = None

    brl: Optional[Brl] = None


class BandwidthPlanAttributesTypedDict(TypedDict):
    region: NotRequired[str]
    locations: NotRequired[List[str]]
    pricing: NotRequired[PricingTypedDict]


class BandwidthPlanAttributes(BaseModel):
    region: Optional[str] = None

    locations: Optional[List[str]] = None

    pricing: Optional[Pricing] = None


class BandwidthPlanTypedDict(TypedDict):
    id: NotRequired[str]
    type: NotRequired[BandwidthPlanType]
    attributes: NotRequired[BandwidthPlanAttributesTypedDict]


class BandwidthPlan(BaseModel):
    id: Optional[str] = None

    type: Optional[BandwidthPlanType] = None

    attributes: Optional[BandwidthPlanAttributes] = None
