#define HTS_CC "gcc"
#define HTS_CPPFLAGS ""
#define HTS_CFLAGS "-fpic -fvisibility=hidden -g -Wall -O2 -fvisibility=hidden"
#define HTS_LDFLAGS "-fvisibility=hidden "
#define HTS_LIBS "-ldeflate -llzma -lbz2 -lz -lm  -lcurl -lcrypto"
