from eskmo.base.mvtype import *
from _typeshed import Incomplete
from eskmo.utils.thread import threadStart as threadStart

PACKAGE_NAME: str
ENV_LOG_LEVEL: str
ENV_APP_KEY: str
ENV_LOG_FILE: str
ENV_LOG_PRINT: str
ENV_PROJECT_NAME: str
CONFIG_LOG_LEVEL: Incomplete
CONFIG_APP_KEY: Incomplete
CONFIG_LOG_FILE: Incomplete
CONFIG_LOG_PRINT: Incomplete
CONFIG_PROJECT_NAME: Incomplete
PREFIX_CHAR: str
LOG_PATTERN: Incomplete
LOG_PATH: Incomplete
LOG_FOLDER: str
LOG_FOLDER_PATH: Incomplete
LOG_FILE_NAME: Incomplete
hash: Incomplete

def ifprint(msg, show: bool = False) -> None: ...

class Logger:
    show: bool
    stop: bool
    logPath: Incomplete
    printQueue: Incomplete
    logFileQueue: Incomplete
    @property
    def show(self): ...
    @show.setter
    def show(self, value) -> None: ...
    @classmethod
    def enable(cls) -> None: ...
    @classmethod
    def disable(cls) -> None: ...
    def __new__(cls): ...
    @staticmethod
    def listenForPrint() -> None: ...
    @staticmethod
    def listenForLogToFile() -> None: ...
    @staticmethod
    def getSignature(logstr): ...
    @staticmethod
    def showStatus() -> None: ...
    @staticmethod
    def nowtime(): ...
    @staticmethod
    def format(msg, windowId: Incomplete | None = None, pid: Incomplete | None = None, type=...): ...
    @staticmethod
    def log(msg, windowId: Incomplete | None = None, logType=..., fgColor=..., bgColor=...) -> None: ...
    @staticmethod
    def logCall(msg, windowId: Incomplete | None = None, type=..., fgColor=..., bgColor=...) -> None: ...
    @staticmethod
    def logFileCall(logstrs=[]) -> None: ...
    @staticmethod
    def addCallback(level, func) -> None: ...
    @staticmethod
    def level(type): ...
    @staticmethod
    def debug(msg, windowId: Incomplete | None = None, **kwargs) -> None: ...
    @staticmethod
    def monitor(msg, **kwargs) -> None: ...
    @staticmethod
    def info(msg, windowId: Incomplete | None = None, **kwargs) -> None: ...
    @staticmethod
    def warning(msg, windowId: Incomplete | None = None, **kwargs) -> None: ...
    @staticmethod
    def error(msg, windowId: Incomplete | None = None, **kwargs) -> None: ...
    @staticmethod
    def fatal(msg, windowId: Incomplete | None = None, **kwargs) -> None: ...
