from enum import Enum
 
class CommandType(Enum):
    POINTENFORCEMENT = 1
    SECTIONENFORCEMENT = 2
    LOCATIONCONFIG = 3
    PING = 4
    CAPTUREIMAGE = 5
    GETLASTIMAGE = 6
    GETNEXTIMAGE = 7
    WRITECAMERAAUX = 8
    STOPENFORCEMENTS = 9
    RESTARTCAMERA = 10
